### ISSUE TITLE
apply "quick fix" for ibid

### ISSUE THREAD

**Issue by warner** [Agoric/SwingSet#55]
#30 describes the problems with our current `ibid` code. This ticket is about just applying the "quick fix" which disables the creation of ibid markers, so that any shared data structures will simply be duplicated in the encoded data. The biggest flaw of this fix is when the marshaller is asked to serialize an object graph with cycles, which will cause infinite recursion and termination of the host. But that's better than the current situation, in which complex data structures will be arbitrarily corrupted as they traverse the serialization process.

**Comment by warner** [comment]
I think 58995449ebecae56cce1a2203a208fddd35a11f3 might have applied this "quick fix". If so, the fix made it into release 0.0.10.

**Comment by erights** [comment]
Well, that's the real fix. And it wasn't quick ;)

**Comment by warner** [comment]
in the old repo. this was SwingSet issue 55
