### ISSUE TITLE
write bang-syntax convertor

### ISSUE THREAD

**Issue by warner** [Agoric/SwingSet#6]
We'd like to be able to use "bang syntax" in userspace Vat code: `x ! foo(y)`. This should be converted into `E(x).foo(y)`. This probably wants to be a plugin to our use of `rollup` when bundling the vat code into a single string.

If we can accomplish that, we should jump ahead to converting it into `E('send', x, 'foo', y)`, and change the E object to match. By providing the method name as a string, we can avoid the need for a Proxy (to glean the method name when it gets looked up), which would be faster and simpler.

The original Promises proposal (http://web.archive.org/web/20161026162206/http://wiki.ecmascript.org/doku.php?id=strawman:concurrency) describes the syntax, although we might need to update some parts of it.

**Comment by katelynsills** [comment]
It looks like we will need to use Babel, and will actually have to fork the Babel parser (formerly Babylon) to be able to do this: https://babeljs.io/docs/en/next/babel-parser.html#will-the-babel-parser-support-a-plugin-system

**Comment by warner** [comment]
I think rollup uses `acorn` (which I think is a parser), does that help us at all?

**Comment by katelynsills** [comment]
It looks like we could write an acorn parser plugin like [this one for bigint](https://github.com/acornjs/acorn-bigint/blob/master/index.js). It seems to be a lot cleaner than plugins for the Babel parser (which is explicitly not supported by them.) The only downside I can see is that an acorn plugin is probably only narrowly useful for Rollup and maybe a few other things, but almost everyone uses Babel. Rollup supports Babel, for instance. Still, it might be helpful to get it working with Acorn and then do Babel at some point in the future.

**Comment by erights** [comment]
How similar are their ASTs?

**Comment by katelynsills** [comment]
I'm still early in the investigation, but they appear to be very similar. Babel-parser says it's based heavily on Acorn. https://babeljs.io/docs/en/next/babel-parser.html

**Comment by erights** [comment]
Good. In that case, if one is substantially easier to get working first, do that one. But let's plan to eventually switch to Babel.

**Comment by katelynsills** [comment]
This has been deprioritized, but to record some of my notes:

Once this is done, we will need to add an argument to `bundleSource` so that the bang transformation is done for vats but not for the kernel. We will also need to throw an error if the bang transformation hasn't been explicitly enabled.

**Comment by erights** [comment]
Why not the kernel?

**Comment by katelynsills** [comment]
Brian might be able to speak to that. I'm not sure myself, but those were the instructions that I got from him. @warner

**Comment by warner** [comment]
We don't have an `E()` wrapper inside the kernel: it expands to things like `syscall.send()` and manages a set of per-Vat Promises, none of which is meaningful from outside of a Vat. So I think we want to see an error if `!` is used inside kernel code.

**Comment by erights** [comment]
Good

**Comment by michaelfig** [comment]
I may have a go at this for Tessie... I'm already using Babel to do the rewrites from Tessie to Jessie.

(And I would like to use Tessie to write vat code for SwingSet.)

**Comment by warner** [comment]
in the old repo. this was SwingSet issue 6
