### ISSUE TITLE
struggling to run contractHost demo: Cannot find module './bundles/kernel'

### ISSUE THREAD

**Issue by dckc** [Agoric/SwingSet#64]
I just checked out 3ae77b4 and tried to follow the instructions in the README, but I lose:

```
connolly@jambox:~/projects/SwingSet$ ./bin/vat run demo/contractHost -- mint
/home/connolly/projects/SwingSet/src/controller.js:1
Error: Cannot find module './bundles/kernel'
Require stack:
- /home/connolly/projects/SwingSet/src/controller.js
- /home/connolly/projects/SwingSet/src/index.js
- /home/connolly/projects/SwingSet/bin/vat
    at Object.<anonymous> (/home/connolly/projects/SwingSet/src/controller.js:1)
connolly@jambox:~/projects/SwingSet$ node --version
```

cc @JoshOrndorff

**Comment by warner** [comment]
Oh, sorry about that, try running `npm run-script build-kernel` first. That gets done automatically when running the tests, but if you're trying to run the demos without first doing `npm test`, you'll have to build the kernel bundle manually.

**Comment by dckc** [comment]
Got it. Thanks.

**Comment by warner** [comment]
in the old repo. this was SwingSet issue 64
