### ISSUE TITLE
require node >= 12?

### ISSUE THREAD

**Issue by warner** [Agoric/SwingSet#99]
@michaelfig noticed that Node 12 has different ordering behaviors than Node 11 (he said this is different than the Node10/11 change to promise-queue -vs- io-queue ordering, and the issue was that Node 11 was delaying something by two turns, whereas Node 12 only delays it by one turn). So the [@agoric/eventual-send](https://github.com/Agoric/eventual-send) package is [going to](https://github.com/Agoric/eventual-send/commit/36a57beb4adeda9bec6aedb69d5da62d05ef9b69) require Node 12.

I don't know if SwingSet would be sensitive to this same ordering issue, but maybe we should make SwingSet require Node 12 or higher anyways, to get consistent behavior anywhere the tests pass.

**Comment by erights** [comment]
OMG, I was there for this normative spec change. I failed to notice that it would cause us an observable difference. There are a few of these. I'll track those down.

Yes, I think we should require Node 12.

**Comment by erights** [comment]
Oops. Didn't mean to close. Reopenning.

**Comment by warner** [comment]
@erights can you add a pointer to the tc39 spec change that precipitated the node-v12 requirement? The one about "some operations require/allow too many turns". I just want folks to be able to see why we had to impose this new requirement.

**Comment by ljharb** [comment]
Perhaps https://github.com/tc39/ecma262/pull/1250 ?

**Comment by erights** [comment]
That's what I was thinking of. It remains to be seen if that's the actual cause of the discrepancy.

Thanks!

**Comment by michaelfig** [comment]
In testing further with a fixed version of eventual-send (i.e. one that has correct behaviour according to what @erights prescribed), I found that having just Node 11 was sufficient.  The Node 12 difference was only exposed by incorrect code in eventual-send.

So, @warner, I'd like to relax this requirement to just need Node 11.  What do you think?

**Comment by warner** [comment]
in the old repo. this was SwingSet issue 99
